### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#13]
**🔴Task 1 : Create New Post Bar** 
- [x] Create a working post button 
- [x] Create a working image upload button 
- [x] Create a working emoji picker 
- [ ] Create a working upload file button 
- [x] Create a working text box background (w:732 h:164)
- [x] Create a working text box that shows "Scribble away ... "   (w:604 h:63  rounded corner radius: 60)
- [x] on click make the text box expanded and editable (w:604 h:291)
- [x] Create a profile picture placeholder 

**🔴Task 2 : Create Scroll Feed** 

- [x] Create a post placeholder (adaptable size)
- [x] Create a title placeholder (font: Poppins size: 20 style: semibold ) 
- [x] Create a text body placeholder (font: Poppins size:20 ) 
- [x] Create a profile picture placeholder 
- [x] Create a fetch request to pull all the posts stored in the database 

**🟡Task 3 : Create a live news feed** 

- [x] Create header "community news" (font: poppins size:20 style: semibold) 
- [x] Create a news title placeholder (font: poppins size:10 style: bold) 
- [x] Create a news body placeholder (font: poppins size:10 ) 
- [ ] Create a live fetch API to get updates news
