### ISSUE TITLE
Side Menu 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#14]
**🔴Task : Side Menu** 

- on click collapse for phone version 
- [x] Create a company logo Placeholder 

**🔴Task : Navigation Bar** 
- regular text (font:Poppins size:18 color:#FFFFFF )
- on selection (font:Poppins size:24 style:underline color:#00A9E5) 
- on selection show background rectangle (color:8DB5C4 opacity 30%) 
- [x] Navigation to "Projects"
- [x] Navigation to "Community Page"
- [x] Navigation to "Sticky Notes"
- [x] Navigation to "Planner"
- [x] Navigation to "Groups"
- [x] Navigation to "Settings"

**🔴Task upgrade to pro button** 

- Make a button with (w:274.14 h:72.36 color: #8DB5C4 corner radius: 15)
- [ ] Navigation to "Upgrade to pro"
