### ISSUE TITLE
Drawing Canvas 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#16]
**🔴Task 1 : Tool Picker** 

- [x] Create a working icon for pen tool
- [x] Create a working icon for text tool 
- [x] Create a working icon for comments 
- [x] Create a working icon for shapes 
- [x] Create a working icon for eraser
- [x] Create a working icon for undo 
- [x] Create a working icon for redo 
- [ ] Create a working icon for chat 
- [ ] Create a working icon for voice call  

**🟡Task 1.1: Color picker**  

- [x] Create a working color picker 

**🔴Task 2 : Chat Interface** 
- [ ] Create a send message button 
- [ ] Create a text box to type message 
- [ ] Create a emoji picker 
- [ ] Create sent message placeholders showing user name 
- [ ] Create a link to database to fetch past chats 

**🟡Task 3 : Connect to voice call Interface** 

- [ ] Create placeholder to show ongoing call
