### ISSUE TITLE
Sticky Notes 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#17]
**🔴Task 1: Add New To Do** 
- [ ] Create a title placeholder "Add new placeholder"
- [x] Create a plus icon button 
- [ ] Link to database to allow saving to do lists 

**🔴Task 2: Display To Do Lists** 
- [ ] Create a vertical scroll 
- [ ] Create a background rectangle (color:#2A2A2A border radius : 15 ) 
- [ ] Create a title place holder (size:24)
- [ ] Create a "last accessed by:" placeholder (size:10)
- [ ] Create a "last saved edit:" placeholder (size:10)
- [ ] Create a "created on:" placeholder (size:10)

**🟢Task 3: Display Saved Sticky Notes** 
- [x] Create a horizontal scroll 
- [ ] Create a rectangle placeholder (color:#EEE598 border radius : 15 )
