### ISSUE TITLE
Planner page 1 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#18]
**🔴Task 1: Add New task** 
- [ ] Create a title placeholder "Add new task"
- [ ] Create a plus icon button 
- [ ] Link to database to allow saving to do lists 

**🔴Task 2: Display Tasks** 
- [ ] Create a vertical scroll 
- [ ] Create title "Tasks In Progress "
- [ ] Create a background rectangle (color:#2A2A2A border radius : 15 ) 
- [ ] Add a border to match priority of task around rectangle 
- [ ] Create a title place holder (size:24)
- [ ] Create a "Team name:" placeholder (size:10)
- [ ] Create a "Priority:" placeholder (size:10)
- [ ] Create a "Task Due:" placeholder (size:10)
- [ ] Create a "Progress:" placeholder (size:10)
- [ ] Create a responsive progress bar 

**🟢Task 3: Display Upcoming tasks** 
- [ ] Create a horizontal scroll 
- [ ] Create title "Upcoming Tasks"
- [ ] Create a rectangle placeholder (color:#2A2A2A border radius : 15 ) 
- [ ] Add a border to match priority of task around rectangle
