### ISSUE TITLE
Planner page 2 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#19]
**🟡Task 1: Create a calendar** 
- [x] Must allow navigation to months 
- [x] on hover change color 
- [ ] on click leads you to corresponding planner page 

**🔴Task 2: Planner page** 
- [x] Create a title with current [Month][year]  (style:bold , size:40 , font: poppins)
- [x] Create a horizontal title row to display days in week 
- [x] Create a horizontal title row to display date of corresponding days 
- [ ] Create a vertical title column to display time (24hrs stating at 12AM)
- [x] Create a clickable grid that corresponds to correct time and date in order to create a new task 
- [ ] Create a task box 
- [ ] Create a "Title:" placeholder 
- [ ] Create a text box to type task title 
- [ ] Create a "Date:" placeholder 
- [ ] Create a "Time:" placeholder 
- [ ] Create a "Priority :" placeholder 
- [ ] Create a priority picker 
- [ ] Create a save button on task box 
- [ ] Link to database in order to save task 

**🟢Task 3: Label picker** 
- [ ] Create a title "Categories" 
- [ ] Create a label "Work" 
- [ ] Create a label "Personal" 
- [ ] Create a label "Social" 
- [ ] Create a label "Other" 
- [ ] Allow to add other label
