### ISSUE TITLE
Company Website 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#20]
### ❕AIMS 

1.  Promote our software company THINKLABS [(company logo)](https://drive.google.com/drive/folders/1-knSY41chq7i3jMnCn0bCMOnBd7CefgH?usp=sharing )
2. A static website 
3. Reflect our vision
4. Promotes features and company products
6. Assessment is on design and content - MAIN FOCUS ‼️  (may use Canva for design) 

### 🛑Tasks 
Use [Figma website](https://help.figma.com/hc/en-us) as inspiration - **Be as creative as possible** since it hold marks to stand out!

- [x] Host website 
- [x] Add company logo 
- [x] Add a about the team 
- [x] Add a "ask for help" page / chat 
- [x] Stick to figma [color palette ](url)
- [x] Add further information on billing options 
- [x] Link other social media handles / email / ways to contact 
- [x] Create a navigation Bar 
eg. 
<img width="1186" alt="Screenshot 2024-01-09 at 16 49 58" src="https://github.com/AdiKsOnDev/ThinkLabs/assets/90443259/cd80992a-cd72-4f3f-8bac-40c2e40f38ce">

- [ ] Add a about the software and its features 
eg. 
![image](https://github.com/AdiKsOnDev/ThinkLabs/assets/90443259/04b18e75-1ea9-4d45-8229-d39a20689e50)

- [ ] Add information on our products and services provided 
eg.
<img width="591" alt="image" src="https://github.com/AdiKsOnDev/ThinkLabs/assets/90443259/a5de3d3a-91ea-455a-9542-dd655e3c35c5">

- [ ] Add information/documentation on upcoming features 
eg. 
![image](https://github.com/AdiKsOnDev/ThinkLabs/assets/90443259/a4480296-1411-445d-887e-a7ab3fec02c5)

- [x] Add short introduction video to THINKLABS (example: [What is THINKLABS](https://help.figma.com/hc/en-us/articles/14563969806359-What-is-Figma-) ) (use Figma prototype to demo) 
<img width="1119" alt="image" src="https://github.com/AdiKsOnDev/ThinkLabs/assets/90443259/5237e709-af12-45c7-8290-063dfc40034c">
