### ISSUE TITLE
Billing information Page 

### ISSUE THREAD

**Issue by aa2149** [AdiKsOnDev/CollaboralHub#23]
### 🟢Task 

- [ ] Make a information card on student plan 
- [ ] Make a information card on education plan 
- [ ] Make a information card on personal plan
